# alacritty-colors collection · Firebrand
# Energy · Scarlet, unmistakably awake

[colors.primary]
background = "#1a0c0c"
foreground = "#e6cccb"

[colors.cursor]
text = "#1a0c0c"
cursor = "#e0452e"

[colors.selection]
text = "#e6cccb"
background = "#3b3361"

[colors.normal]
black = "#302c2c"
red = "#e3513b"
green = "#57e33b"
yellow = "#e3a63b"
blue = "#7173eb"
magenta = "#e33bae"
cyan = "#3bd8e3"
white = "#cac4c4"

[colors.bright]
black = "#5b5252"
red = "#e68d7f"
green = "#91e67f"
yellow = "#e6c17f"
blue = "#7f81e6"
magenta = "#e67fc5"
cyan = "#7fdfe6"
white = "#f0efef"

[colors.dim]
black = "#201d1d"
red = "#ae3928"
green = "#3fae28"
yellow = "#ae7e28"
blue = "#282aae"
magenta = "#ae2884"
cyan = "#28a5ae"
white = "#a39999"

