# alacritty-colors collection · Honeyed Dusk
# Warmth · Gold going down

[colors.primary]
background = "#171208"
foreground = "#e6d9bd"

[colors.cursor]
text = "#171208"
cursor = "#e0b040"

[colors.selection]
text = "#e6d9bd"
background = "#2f3b59"

[colors.normal]
black = "#302f2c"
red = "#da6944"
green = "#5dda44"
yellow = "#daad44"
blue = "#557edd"
magenta = "#da44ab"
cyan = "#44dac3"
white = "#cac8c4"

[colors.bright]
black = "#5b5852"
red = "#df9c86"
green = "#95df86"
yellow = "#dfc486"
blue = "#86a1df"
magenta = "#df86c3"
cyan = "#86dfd2"
white = "#f0f0ef"

[colors.dim]
black = "#201f1d"
red = "#a64e30"
green = "#44a630"
yellow = "#a68330"
blue = "#3054a6"
magenta = "#a63081"
cyan = "#30a694"
white = "#a3a099"

